---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - name: Check for updates
    ansible.builtin.dnf:
      state: latest
      update_cache: yes
      
  
  - name: Install updates
    ansible.builtin.dnf:
      update_only: yes
      autoremove: yes
