---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - name: Check for updates
    ansible.builtin.dnf:
      dnf: state=latest update_cache=yes 
  
  - name: Install updates
    ansible.builtin.dnf:
      dnf: update_only autoremove=yes
