---
- gather_facts: true
  become: yes
  become_method: sudo

  tasks:
    - name: install yum-utils if needed
      ansible.builtin.dnf:
        name: yum-utils
        state: present  
    - name: check if reboot is required
      ansible.builtin.shell:
        cmd: "needs-restarting -r -s"
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      failed_when: needs_restarting.rc == 0  
    - name: do reboot if needed
      ansible.builtin.reboot:
      when: needs_restarting.rc == 1
