---
- hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
  - name: Check for updates
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
  - name: Install updates
    apt: upgrade=dist force_apt_get=yes
